### ISSUE TITLE
Error with Lollipop - Resolved

### ISSUE THREAD

**Issue by GoogleCodeExporter** [manyixu/android-rome-feed-reader#32]
```
I ran into the following error (see attached for full stack):

Caused by: java.lang.NullPointerException: in == null
    at java.util.Properties.load(Properties.java:246)
    at com.google.code.rome.android.repackaged.com.sun.syndication.io.impl.PropertiesLoader.<init>(PropertiesLoader.java:74)

I resolved this by using the same workaround as described in this wiki for pre 
2.2:

https://android-rome-feed-reader.googlecode.com/svn-history/r132/wiki/Android21A
ndEarlierWorkaround.wiki

Specifically, I added the following to my doInBackground onPreExecute:

    Thread.currentThread().setContextClassLoader(getClass().getClassLoader());
```

Original issue reported on code.google.com by `brian.ca...@gmail.com` on 18 Apr 2015 at 1:32

Attachments:
- [error_with_rome.txt](https://storage.googleapis.com/google-code-attachments/android-rome-feed-reader/issue-32/comment-0/error_with_rome.txt)

**Comment by GoogleCodeExporter** [comment]
```
Note this was tested specifically with a Samsung Galaxy S6 running stock 5.0.2
```

Original comment by `brian.ca...@gmail.com` on 18 Apr 2015 at 1:38

**Comment by GoogleCodeExporter** [comment]
```
Hi Brian could you please explain better where to place that piece of code? i'm 
experiencing this issue on my application on Samsung devices updatet to 
lollipop.
```

Original comment by `dilaurog...@gmail.com` on 5 May 2015 at 1:46

**Comment by GoogleCodeExporter** [comment]
```
Hi, I just did exactly what I specified, put it in the onPreExecute, since I'm 
running the actual check in a separate thread. Just make sure you execute that 
line of code somewhere before querying.

Note I tested my app before the fix on my Nexus 9 and it did not have the same 
issue. May be a regression in 5.0.2 lollipop.
```

Original comment by `brian.ca...@gmail.com` on 5 May 2015 at 4:07

**Comment by GoogleCodeExporter** [comment]
```
Hi Brian, excuse me for the delay..
Your fix works! Now i don't have that problem anymore :)
thanks
```

Original comment by `dilaurog...@gmail.com` on 21 May 2015 at 3:22
